### ISSUE TITLE
Aws::S3::Errors::InvalidArgument - Invalid argument.

### ISSUE THREAD

**Issue by jlebrijo** [janko/tus-ruby-server#20] opened 2020-05-14 16:17 UTC
Hi!

I am experiencing this error when I try to upload a file:
```
I, [2020-05-14T18:08:46.914272 #12057]  INFO -- : [Aws::S3::Client 400 0.080107 0 retries] create_multipart_upload(content_type:"text/csv",content_disposition:"inline; filename=\"tmp.csv\"; filename*=UTF-8''tmp.csv",bucket:"weopt-local",key:"[FILTERED]") Aws::S3::Errors::InvalidArgument Invalid argument.
```

I am using this config in initializer:
```
require "tus/server"
require "tus/storage/s3"

Tus::Server.opts[:storage] = Tus::Storage::S3.new(
    access_key_id:     ENV['S3_ACCESS_KEY'], # "AccessKey" value
    secret_access_key: ENV['S3_SECRET'], # "SecretKey" value
    endpoint:          ENV['S3_ENDPOINT'],   # "Endpoint"  value
    bucket:            ENV['GCLOUD_BUQUET'],     # name of the bucket you created
    region:            ENV['GCLOUD_REGION'],
    # prefix:            'files',
    logger: Logger.new(STDOUT),
    force_path_style:  true,
    )
Tus::Server.opts[:redirect_download] = true # redirect download requests to S3
```

Trying with AWS sdk, I can upload a file with this code:
```
  s3=Aws::S3::Resource.new(
      access_key_id:     ENV['S3_ACCESS_KEY'], # "AccessKey" value
      secret_access_key: ENV['S3_SECRET'], # "SecretKey" value
      endpoint:          ENV['S3_ENDPOINT'],   # "Endpoint"  value
      # bucket:            ENV['GCLOUD_BUQUET'],     # name of the bucket you created
      region:            ENV['GCLOUD_REGION'],
      # prefix:            'files',
      force_path_style:  true,
      )
  obj = s3.bucket(ENV['GCLOUD_BUQUET']).object('key')
  obj.upload_file('tmp/tmp.csv')
```

Can you help, please?

**Comment by janko** [comment] 2020-05-14 17:04
What S3-compatible service are you uploading to? I see mentions of google cloud here. It's possible that this service has slightly different behaviour than S3 does, and that it doesn't accept some arguments.

If you think this happens with AWS S3 as well, could you try reproducing it using the tus-ruby-server's S3 storage directly? For example:

```rb
require "tus/storage/s3"
require "stringio"

s3 = Tus::Storage::S3.new(...)
s3.create_file("foo", info = {})
s3.patch_file("foo", StringIO.new("content"), info)
s3.finalize_file("foo", info)
```

**Comment by jlebrijo** [comment] 2020-05-14 18:32
Error is raising when try to create file:
![Selection_331](https://user-images.githubusercontent.com/553507/81971863-0da20d80-9622-11ea-9ec7-c0503f1dd45a.png)

**Comment by janko** [comment] 2020-05-14 19:14
How is your S3 bucket configured? The following script executes without errors for me:

```rb
# credentials that have permissions for creating buckets
ENV["AWS_ACCESS_KEY_ID"]     = "..."
ENV["AWS_SECRET_ACCESS_KEY"] = "..."
ENV["AWS_REGION"]            = "..."

require "tus/storage/s3"
require "securerandom"

# create the bucket
client = Aws::S3::Client.new
client.create_bucket(bucket: bucket = SecureRandom.hex)

at_exit do
  client.delete_object(bucket: bucket, key: "foo")
  client.delete_object(bucket: bucket, key: "foo.info")
  client.delete_bucket(bucket: bucket)
end

storage = Tus::Storage::S3.new(bucket: bucket)
storage.create_file("foo", info = {})
storage.patch_file("foo", StringIO.new("content"), info)
storage.finalize_file("foo", info)
```

**Comment by jlebrijo** [comment] 2020-05-14 21:05
Raises the same error on `storage.create_file`.

But if you create the file from Aws::S3::Client it works:
```
client = Aws::S3::Client.new
client.create_bucket(bucket: bucket = SecureRandom.hex)
obj = client.bucket(bucket).object('key')
obj.upload_file('tmp/tmp.csv')
```
Seems about the difference between two ways to create an object.

**Comment by janko** [comment] 2020-05-14 21:38
Yes, the tus server storage will initiate a multipart upload (as you can see from the exception backtrace), which the other will do a simple PUT upload. So, they’re different operations.

Since this works for me, it’s your responsibility to provide more information for reproducing the error. For starters you never answered whether you’re using S3 or an S3-comaptible service.

I will close this now as it doesn’t appear to be a bug in tus-ruby-server.

**Closed by janko** 2020-05-14 21:38 UTC

**Comment by jlebrijo** [comment] 2020-05-15 07:07
Yes, thanks for your help.

It is Google Cloud Storage service. It is a S3 compatible service. I gave 'Admin Storage' role permission to my user, and created S3 keys for it.

**Comment by jlebrijo** [comment] 2020-05-15 08:16
Just found that GoogleStorage and Amazon S3 do not manage multipart uploads the same way: https://www.zenko.io/blog/four-differences-google-amazon-s3-api/

Google suggests resumable uploads for big files: https://cloud.google.com/storage/docs/resumable-uploads
